### ISSUE TITLE
Can't find encrypt file and some other errors

### ISSUE THREAD

**Issue by Yesssaag** [pogodevorg/pgoapi#212]
Traceback (most recent call last):
  File "C:\Users\iamye\Desktop\pk api\pokecli.py", line 139, in <module>
    main()
  File "C:\Users\iamye\Desktop\pk api\pokecli.py", line 134, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "C:\Users\iamye\Desktop\pk api\pgoapi\pgoapi.py", line 150, in function
    return request.call()
  File "C:\Users\iamye\Desktop\pk api\pgoapi\pgoapi.py", line 244, in call
    default_libraries = get_lib_paths()
  File "C:\Users\iamye\Desktop\pk api\pgoapi\utilities.py", line 221, in get_lib_paths
    raise Exception(err)
Exception: Could not find win32 encryption library C:\Users\iamye\Desktop\pk api\pgoapi\lib\libpcrypt-windows-i686.dll

**Comment by gman-php** [comment]
you probably wanna check out github.com/pokelibs/pgoapi-libs.git
